
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel2"><font color="black">Privacy Policy</font></h4>
      </div>
      <div class="modal-body">
    <font color="black">This privacy policy applies to your use of the CollegeConnect.in website located at www.collegeconnect.in. The terms \"we\", \"us\", and \"CollegeConnect\" refer to CollegeConnect.in and the terms \"you\" and \"your\" refer to you, as a user of CollegeConnect.in. The term \"personal information\" means information that you provide to us which personally identifies you to be contacted or identified, such as your name, phone number, email address, articles and any other data that is tied to such information. By using CollegeConnect, you agree to be bound by terms of this privacy policy. If you do not agree with these terms, do not use CollegeConnect.
I. Information we collect and how we use it
We use commercially reasonable efforts to ensure that the collection of personal information is limited to that which is necessary to fulfill the purposes identified below. If we use your information in a manner different than the purpose for which it is collected, then we will ask you for your consent prior to such use.
Account information.
If you create an account to take advantage of the full range of services offered on CollegeConnect, we ask for and record personal information such as your name, email address,  your articles(if you upload). We use your email address to send you updates, news. We use your posts to make it public so that people can know you. There will be no extra contents which you dont want to share. Your articles and stories will be displayed the same as what you upload.
Submissions.
We store and may publicly display your submissions in order to provide the services that we offer. When we display your submissions, we do so together with your account name (first name and last initial). The term \"submissions\" refers to the information that you submit or post to CollegeConnect for public display, such as articles, snapshots, and the information that you display as part of your account profile.
Feedback.
If you contact us to provide feedback, register a complaint, or ask a question, we will record any personal information and other content that you provide in your communication so that we can effectively respond to your communication.
Activity.
We record information relating to your use of CollegeConnect, such as the searches you undertake, the pages you view, your browser type, IP address, location, requested URL, referring URL, and timestamp information. We use this type of information to administer CollegeConnect and provide the highest possible level of service to you. We also use this information in the aggregate to perform statistical analyses of user behavior and characteristics in order to measure interest in and use of the various areas of CollegeConnect. You cannot be identified from this aggregate information.
Cookies.
We send cookies to your computer in order to uniquely indentify your browser and improve the quality of our service. The term \"cookies\" refers to small pieces of information that a website sends to your computer's hard drive while you are viewing the site. We may use both session cookies (which expire once you close your browser) and persistent cookies (which stay on your computer until you delete them). Persistent cookies can be removed by following your browser help file directions. If you choose to disable cookies, some areas of CollegeConnect may not work properly or at all. CollegeConnect uses third party tools, who may collect anonymous information about your visits to CollegeConnect using cookies, and interaction with CollegeConnect products and services. Such third parties may also use information about your visits to Zomato products and services and other web sites to target advertisements for Zomato's products and services. No PII is collected or used in this process. These third parties do not know or have access to the name, email address, biodata or any personally identifying information about CollegeConnect's users. CollegeConnect users can opt-out of sharing this information with third parties by deactivating cookies, the process of which varies by browser to browser. Please refer to the help file of your browser to understand the process of deactivating Cookies on your browser.
Enforcement.
We may use the information we collect in connection with your use of CollegeConnect (including your personal information) in order to investigate, enforce, and apply our Terms of Service and Privacy Policy.
II. Transfer of information
We may distribute your submissions to third parties, as permitted pursuant to our Terms of Service. The third parties may in turn publicly display or publish your submissions in connection with their own websites and media platforms. When we distribute your submissions to third parties, we typically include your account name (but not your personal information unless you include your personal information in your submissions).
We may share your personal information with third parties to provide you with services that we offer through CollegeConnect conduct quality assurance testing, facilitate creation of accounts, provide technical and customer support, or provide specific services, such as synchronization of your contacts with other software applications, in accordance with your instructions. These third parties are required not to use your personal information other than to provide the services requested by you.
We may share your personal information with our parent company, subsidiaries, joint ventures, or other companies under a common control (collectively, \"Affiliates\") that we may have now or in the future, in which case we will require them to honor this Privacy Policy. If another company acquires our company or our assets, that company will possess your personal information, and will assume the rights and obligations with respect to that information as described in this Privacy Policy.
We may disclose your personal information to third parties in a good faith belief that such disclosure is reasonably necessary to (a) take action regarding suspected illegal activities; (b) enforce or apply our Terms of Service and Privacy Policy; (c) comply with legal process, such as a search warrant, subpoena, statute, or court order; or (d) protect our rights, reputation, and property, or that of our users, affiliates, or the public. Please note that we are not required to question or contest the validity of any search warrant, subpoena or other similar governmental request that we receive.
We may disclose information in the aggregate to third parties relating to user behavior in connection with actual or prospective business relationship with those third parties, such as advertisers and content distributors. For example, we may disclose the number of users that have been exposed to, or clicked on, advertising banners.
III. Others' information.
You may choose to provide us with another person's e-mail address so that person may be invited to create an account on this website and become your friend. We use this information to contact and, if necessary, remind that person about the invitation. By providing us with another person's e-mail address, you represent to us that you have obtained the consent of the person concerned as regards such disclosure to us of their personal information. All invitees are provided with the option not to receive further invitations. We may disclose such information if required to do so in order to comply with legal process, as described above.
IV. Links
CollegeConnect may contain links to third party websites to which we have no affiliation. Except as set forth herein, we do not share your personal information with those third parties, and are not responsible for their privacy practices. We suggest you read the privacy policies on all such third party websites.
V. Controlling your personal data.
To the extent you include personal information in your submissions (such as a photo of yourself), third parties may be able to identify you, associate you with your user account, and contact you. Third parties can also associate you with your user account using the member lookup feature on CollegeConnect but only if the third party already knows your full name and you include information in your submission that allows the third party to distinguish you from other users who might share the same full name. Please do not include information in your submissions that you expect to keep private. In addition, you can reduce the risk of being personally identified by choosing a fictitious account name, though doing so could detract from the credibility of your submissions.
VI. Security
Your account is password protected. We use industry standard measures to protect the personal information that is stored in our database. We limit the access to your personal information to those employees and contractors who need access to perform their job function, such as our customer service personnel. If you have any questions about the security on CollegeConnect please contact us. Although we take appropriate measures to safeguard against unauthorized disclosures of information, we cannot assure you that your personal information will never be disclosed in a manner that is inconsistent with this Privacy Policy.
You hereby acknowledge that CollegeConnect is not responsible for any intercepted information sent via the internet, and you hereby release us from any and all claims arising out of or related to the use of intercepted information in any unauthorized manner.
VII. Terms and modifications to this Privacy Policy.
We may modify this Privacy Policy at any time, and we will post any new versions on this page. If we make any material changes in the way we use your personal information, we will notify you by sending an e-mail to the last e-mail address you provided to us and/or by prominently posting notice of the changes on our website. Any such changes will be effective upon the earlier of thirty (30) calendar days following our dispatch of an e-mail notice to you or thirty (30) calendar days following our posting of notice of the changes on our website. These changes will be effective immediately for new users of CollegeConnect. Please note that at all times you are responsible for updating your personal information to provide us with your most current e-mail address. In the event that the last e-mail you have provided us is not valid, or for any reason is not capable of delivering to you the notice described above, our dispatch of the e-mail containing such notice will nonetheless constitute effective notice of the changes described in the notice. In any event, changes to this Privacy Policy may affect our use of personal information that you provided us prior to our notification to you of the changes. If you do not wish to permit changes in our use of your personal information, you must notify us prior to the effective date of the changes that you wish to deactivate your account with us. Continued use of CollegeConnect following notice of such changes shall indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes.

</font>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       
      </div>
    </div>
  </div>
</div>